language: objective-c
branches:
  only:
    - test
env:
  matrix:
    - 'PLATFORM="ios"'
    - 'PLATFORM="android" ANDROID_VERSION="19"'
  global:
    - secure: i0VasC4lz8kXYghQ2wrfxsPxGd8ra311HXLPEpiCEQfWXLTHEhh06DOnhVQi5asd3L5//B24kUXBPpiNOh5+yL4dSXLysuq2LkIKAxE5sb3feXrey9fepqKLxfTp3IbZHkW9Bbb37ukBtKe5bUaOKTegeF9e/sNutBvLC490aDg+QrSEyPPTKNr86pnXZuqSD+L25XYsg8Z/Rdk8DpjE8yLztdxsKQRAns9ta60PxXRiTY4vpjw0UigcOd7wsu8GysOqqUpv+y7QodubWU3cgbhOHW0kEdWe1lo62dDpe7DboEVZ9J3dMEEaXvth2dQmH7szwkHSuMvz4jh9kDBFO2w3TPXCGazQ8jjgJ89r5TSl9O8Cxi1fYmLyruWGSmaZqBVd/MWbPVY+gaySlLEN7EljuQrCZYa3F98lVQpa97aJgg/zGUfyEQ12UFm35rjd3UaxSeoDCihRGwRzNa09cRXa7zbq2JCCcEu2sWLerXo1ye9+QXlm3bDN7pnPt1TYgv+QV3DpCF55Asndz5HC/Vg2AH+Z9H4Fs62zjowQtmUY+AQzFX27tO3g3PZcbnMuYeeuZNyK29bDKXU+Po+/FSCEBGzmy+tEduuOIaPALiCNxgFqpt6fLsUttGKZtqC2pVuEo/QXgtD8yAcd7LwH4I3oq8ZTfelVOAdHSY+fXtI=

matrix:
  fast_finish: true
  allow_failures:
    - env: 'PLATFORM="android" ANDROID_VERSION="19"'
before_install:
  - export ANDROID_HOME=$PWD/android-sdk-macosx
  - export ANDROID_SDK=$ANDROID_HOME
  - 'export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools'
install:
  - npm install -g titanium alloy tishadow gulp ktorz/ticalabash
  - npm install
  - titanium login travisci@appcelerator.com travisci
  - titanium sdk install latest --no-progress-bars
  - "gulp 'install:android_sdk'"
before_script:
  - "gulp 'start:emulator'"
  - "gulp 'config:tiapp' --test"
script:
  - "gulp 'test:jasmine'"
  - "gulp 'test:calabash'"
